title:              "OPENING JIEUN WOLRD"
tagline:            ""
email:              "xxjieun0711@gmail.com"
description:        "This blog is a glimpse into my adventures."
author:             "Jieun Lee"
baseurl:            "/"
url:                "https://openingjieun.world"
locale:             "ko_KR"
thumbnail:          '/img/111.jpg' 


# Social Profiles
twitter_username:   twitter_username
instagram_username: /jieun_june__lee/
facebook_username:  facebook_username
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           3
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
# 블로그 disqus shortname
disqus:
  shortname: openingjieun
